name: Day 44 - Secrets

on: [push]

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: false"
          else
            echo "The secret is set: true"
          fi

      - name: Try printing secret
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

     
      - name: Create file
        run: echo "Hello DevOps" > report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-report
          path: report.txt
